spring.config.import=optional:file:./.env[.properties]
spring.application.name=hostelchatbot
server.port=${PORT:8080}
spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.database=hostelchatbot
spring.data.mongodb.auto-index-creation=true
jwt.secret=${JWT_SECRET}
ai.provider=${AI_PROVIDER}
ai.groq.api-key=${GROQ_API_KEY}
ai.groq.model=${GROQ_MODEL}
